# Default values for appstore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # -- repository where image is located
  repository: containers.renci.org/helxplatform/appstore
  # -- pull policy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag:

fetcherImage:
  # -- repository where image is located
  repository: helxplatform/url-fetch
  # -- pull policy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

# -- credentials for a private repo
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

networkPolicyLabels: {"role": "appstore"}

podAnnotations: {}

# -- Set the log level for the application. Overriden to be "debug" if DEBUG setting is true in the configmap.
logLevel: "info"

updateStrategy:
  # -- 'RollingUpdate' or 'Recreate'. Must use Recreate if mounting PVCs due to multi-attach errors.
  type: Recreate

serviceAccount:
  # -- specifies whether a service account should be created
  create: true
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

service:
  type: ClusterIP
  port: 80
  name: http

resources:
  limits:
    cpu: 400m
    memory: 625Mi
  requests:
    cpu: 100m
    memory: 300Mi

security:
  isolatedApps: true

# -- Choose http or https for the protocol that is used by external users to access
# the appstore web service.
ACCOUNT_DEFAULT_HTTP_PROTOCOL: http

# -- Set environment variables from a file.
SET_BUILD_ENV_FROM_FILE: false

nodeSelector: {}

tolerations: []

affinity: {}

ambassador:
   # -- register appstore with ambassador flag: <True or False>
   flag: true

# -- set the theme for appstore (bdc, braini, restartr, scidas)
djangoSettings: bdc
# -- Allow for a custom entrypoint command via the values file.
appstoreEntrypointArgs: "make start"

artillery:
  # -- When either smokeTest or loadTest is true, set CREATE_TEST_USERS, TEST_USERS_PATH under django settings.
  smokeTest: false
  loadTest: false
  loadDuration: 10
  loadArrivalRate: 10

# -- Various settings for helx-ui which will get expressed as env variables in container
helx_ui:
# -- REACT_APP_ANALYTICS (string) HeLx Mixpanel project analytics token
  REACT_APP_ANALYTICS: ""
# -- REACT_APP_APPSTORE_ASSET_BRANCH: (string) branchname of appstore branch
  REACT_APP_APPSTORE_ASSET_BRANCH: "master"
# -- REACT_APP_HELX_SEARCH_URL: (url)  URL of tranql
  REACT_APP_HELX_SEARCH_URL: ""
# -- REACT_APP_SEMANTIC_SEARCH_ENABLED: (boolean) Enable/Disable helx-ui search.
  REACT_APP_SEMANTIC_SEARCH_ENABLED: "true"
# -- REACT_APP_UI_BRAND_NAME: (string)
# values: cat, braini, eduhelx, eduhelx-chip690, eduhelx-sandbox, restartr, scidas, tracs
  REACT_APP_UI_BRAND_NAME: ""
# -- REACT_APP_WORKSPACES_ENABLED: (boolean) Enable/Disable workspaces
  REACT_APP_WORKSPACES_ENABLED: "true"

gunicorn:
  # -- Set the number of gunicorn workers.
  workers: 5

django:
  # -- create test users for load testing
  CREATE_TEST_USERS: "false"
  # -- parent directory where the users.txt would be mounted
  TEST_USERS_PATH: "/usr/src/inst-mgmt/artillery-tests/payloads"
  # -- secret file deployed on the cluster to fetch the test users
  TEST_USERS_SECRET: "test-users-secret"
  # -- user emails for oauth providers
  AUTHORIZED_USERS: ""
  # -- user emails to remove from an already-existing database
  REMOVE_AUTHORIZED_USERS: ""
  # -- Defaults to "master". Specify "develop" to switch.
  DOCKSTORE_APPS_BRANCH: "v1.6.0"
  ###################################################
  APPSTORE_DJANGO_USERNAME: "admin"
  APPSTORE_DJANGO_PASSWORD: ""
  # -- show Django log in fields (true | false)
  ALLOW_DJANGO_LOGIN: ""
  # -- show SAML log in fields (true | false)
  ALLOW_SAML_LOGIN: ""
  # -- email of account to use for outgoing emails
  EMAIL_HOST_USER: ""
  # -- password of account to use for outgoing emails
  EMAIL_HOST_PASSWORD: ""
  # -- Specify URL to use for the "Image Download" link on the top part of website.
  IMAGE_DOWNLOAD_URL: ""
  # -- idle timeout for user web session
  SESSION_IDLE_TIMEOUT: 3600
  # -- list of appstore registration emails
  RECIPIENT_EMAILS: ""
  DEV_PHASE: "prod"

oauth:
  existingClaim: false
  claimName: appstore-oauth-pvc
  storageClass:
  # -- oauth providers separated by commas (google, github)
  OAUTH_PROVIDERS: ""
  GITHUB_NAME: ""
  GITHUB_KEY: ""
  GITHUB_SITES: ""
  GITHUB_CLIENT_ID: ""
  GITHUB_SECRET: ""
  GOOGLE_NAME: ""
  GOOGLE_KEY: ""
  GOOGLE_SITES: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_SECRET: ""

saml:
  cache:
    enabled: false
    claimName: "saml-cache"
    storageSize: "20M"
    storageClass: ""
    FETCH_FILE: "/data/saml_metadata.xml"
    FETCH_INTERVAL: "60000"
    APPSTORE_DIRECTORY: "/saml"
    APPSTORE_FILE: "saml_metadata.xml"
  AUTHORITY_URL: ""
  ASSERTION_URL: ""
  ENTITY_ID: ""

irods:
  # -- enable irods support (true | false)
  enabled: false
  BRAINI_RODS: ""
  NRC_MICROSCOPY_IRODS: ""
  RODS_USERNAME: ""
  RODS_PASSWORD: ""
  IROD_COLLECTIONS: ""
  IROD_ZONE: ""


irodsUnbranded:
  enabled: False
  RODS_USERNAME: ""
  RODS_PASSWORD: ""
  IROD_ZONE: ""
  IROD_PORT: ""
  IROD_HOST: ""
  IROD_USER_VALUES: {}


apps:
  DICOMGH_GOOGLE_CLIENT_ID: ""
  DATASOURCE_CONNECTION_URL: ""
  DATASOURCE_PASSWORD: ""
  FLYWAY_DATASOURCE_CONNECTION_URL: ""
  FLYWAY_DATASOURCE_PASSWORD: ""
  DATASOURCE_USERNAME: "ohdsi"
  FLYWAY_DATASOURCE_USERNAME: "ohdsi"
  # -- PUID variable in webtop specifies the UID to switch the user to after initialization.
  WEBTOP_PUID: "1000"
  # -- PGID variable in webtop specifies the GID to switch the user to after initialization.
  WEBTOP_PGID: "1000"

appStorage:
  existingClaim: false
  claimName:
  storageSize: 2Gi
  storageClass:

userStorage:
  # -- Create a PVC for user's files.  If false then the PVC needs to be created
  # outside of the appstore chart.
  createPVC: false
  storageSize: 10Gi
  storageClass:
  nfs:
    createPV: false
    path:
    server:

# Add any extra environment variables not already defined in the chart.
extraEnv: {}

# -- Set to true, when using blackbalsam.
useSparkServiceAccount: false

tycho:
  # -- Application processes launched will run as this user.
  runAsUser: 0
  # -- Application processes launched will have this group permissions.
  runAsGroup: 0
  # -- Application processes launched will also be part of this supplimentary group.
  fsGroup: 0
  # -- Start the init container to take care of any needed tasks before the
  # main container is started.  This can be to create certain directories or
  # set file permissions.
  enableInitContainer: true
  # -- Init processes will run as this user.
  initRunAsUser: 0
  # -- Init processes will have this group permissions.
  initRunAsGroup: 0
  # -- Create Home and shared directories for users.
  createHomeDirs: true
  # -- directory that will be used to mount user's home directories in
  parent_dir: "/home"
  # -- Name of directory to use for a user's home directory.  If null then the
  # user's username will be used.
  subpath_dir: null
  # -- name of directory to use for shared data
  shared_dir: "shared"
  # -- Resource for Tycho init container. Defaults cpus|250m memory|250Mi
  init:
    resources:
      cpus: 250m
      memory: 250Mi

global:
  # -- the name of the PVC to use for user's files
  stdnfsPvc: stdnfs
  # -- specify the id of the ambassador for Tycho-launched services.
  ambassador_id:

#############################################################################
# -- appstore database settings
db:
  name: appstore
  host: postgresql
  port: 5432

# -- postgresql settings
postgresql:
  enabled: true
  global:
    # -- postgresql credentials
    postgresql:
      auth:
        postgresPassword: "adminPass"
        database: "appstore-oauth"
        username: "renci"
        password: "renciAdmin"
  # -- postgresql labels
  primary:
    labels: {"np-label": "appstore-db"}
    podLabels: {"np-label": "appstore-db"}
  # -- postgresql logs
  audit:
    logHostname: true
    logConnections: true
  # -- postgresql persistence storage
  persistence:
    existingClaim: "appstore-postgresql-pvc"
    storageClass:
  volumePermissions:
    enabled: true
  # -- enable/disable postgresql network policy, allows traffic to and from appstore pod only.
  networkPolicyEnabled: true
